services:
  db:
    container_name: postgres
    image: postgres:15.5
    environment:
      POSTGRES_USER: shashank
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  shashank-api:
    container_name: shashank-api
    image: shashank446/shashank-api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/customer"
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  shashank-react:
    container_name: shashank-react
    image: shashank446/shashank-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - shashank-api
    restart: unless-stopped





networks:
  db:
    driver: bridge

volumes:
  db:

