services:
  db:
    container_name: postgres
    image: postgres:15.5
    environment:
      POSTGRES_USER: shashank
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  shashank-api:
    container_name: shashank-api
    image: shashank446/shashank-api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/customer"
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped



networks:
  db:
    driver: bridge

volumes:
  db:

