server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"


spring:
  datasource:
    url: jdbc:postgresql://awseb-e-7p728mgmti-stack-awsebrdsdatabase-uzcw90r45zh6.c9kkk2eu6u16.ap-south-1.rds.amazonaws.com:5432/ebdb
    username: shashank
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet